### ISSUE TITLE
Update to use yarn cache

### ISSUE THREAD

**Issue by pcavagna** [synapsestudios/hapi-api-template#21]
We should be able to mount the host's yarn cache into our node containers. Hopefully this won't require us to run a bash script or some other tomfoolery.

Options are:

- copy the yarn cache from inside our containers to a yarncache directory in the project that is .gitignored. yarn install will run for each container and populate the cache and can use that cache for each run. The cache won't be shared between projects.
- Force everybody to change their yarn cache directory to a standard directory that we all agree to. Then we can just mount that directory as a volume. Projects will get to share cache.
- Write a bash script that starts the containers and dynamically adds the yarn cache volume using the output from `yarn cache dir` command.

**Comment by spruce-bruce** [comment]
This is probably an obsolete issue. Need to discuss changing to npm 5 and making use of npm cache inside of our containers instead.
